#!/bin/sh
# aspm - main script -*- mode: Sh; coding: utf-8; -*-
#
# The MIT License (MIT)
#
# Copyright (c) 2015 Sekadar Awan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

unset -v CDPATH
unset -v GREP_OPTIONS
unset -v PATH

PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

if [ -e etc/aspm/aspm.conf ]; then
  . etc/aspm/aspm.conf
fi

declare -r ASPM_DIR="var/lib/aspm"
declare -r ASPM_CACHE_DIR="var/cache/aspm"
declare -r PKG_LIST="${ASPKG_DIR}/pkglist"
declare -r PKG_SRC_DIR="${ASPKG_DIR}/sources"
declare -r PKG_LIST_INSTALLED="${ASPKG_DIR}/INSTALLED"
declare -r PKG_LIST_DEPS="${ASPM_DIR}/DEPS"

if [ -d usr/lib/aspm ]; then
  for f in usr/lib/aspm/* ; do
    . "${f}"
  done
fi

do_install() {
  local force only_fetch only_build nonstop resume OPTIND
  local tmp_pkg aspkg
  force="NO"
  only_fetch="NO"
  only_build="NO"
  nonstop="NO"
  resume="NO"

  OPTIND=1
  while getopts Ffbcr opts; do
    case "${opts}" in
      F)
        force="YES"
        ;;
      f)
        only_fetch="YES"
        ;;
      b)
        only_build="YES"
        ;;
      c)
        nonstop="YES"
        ;;
      r)
        resume="YES"
        ;;
    esac
  done
  shift $(( ${OPTIND} - 1 ))

  local pkg
  for pkg in "${@}"; do
    tmp_pkg="$( get_aspkg ${pkg} )"
    case ${?} in
      0)
        ;;
      1)
        if [ "X${nonstop}" != "XYES" ]; then
          echo "Error: package ${pkg} is not found in any repository."
          return 1 # TODO: exit status
        else
          continue
        fi
        ;;
      2)
        if [ "X${nonstop}" != "XYES" ]; then
          echo "Error: package ${pkg} is found in more than one repositories."
          echo "${tmp_pkg}"
          return 2 # TODO: exit status
        else
          continue
        fi
        ;;
    esac

    aspkg+=" ${tmp_pkg}"

    echo "${tmp_pkg}" # test prototyping

  done

  if [ "X${only_fetch}" = "XYES" ]; then
    if [ "X${only_build}" = "XYES" ]; then
      echo "-f and -b options are mandatory."
      return 2 # TODO: exit status
    fi
  fi

  get_src_file "${aspkg}"
  build_package "${aspkg}"

  echo "${aspkg#?}"
}

case ${1} in
  install|in)
    shift
    do_install "$@"
    ;;
  update|up)
    shift
    do_update
    ;;
  remove|rm)
    shift
    do_remove "$@"
    ;;
  *) echo "usage: ${0}";;
esac
# vim: ft=sh:ts=4:sw=2:sts=2:syn=sh:et
