#!/bin/sh
# aspm - main script -*- mode: Sh; coding: utf-8; -*-
#
# The MIT License (MIT)
#
# Copyright (c) 2015 Sekadar Awan
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH

. ./aspm.conf

. ./libaspm.sh

PKGLIST="${ASPKG_DIR}/pkglist"

do_install() {
  local force only_fetch only_build nonstop resume OPTIND
  local tmp_pkg count pkg
  force="NO"
  only_fetch="NO"
  only_build="NO"
  nonstop="NO"
  resume="NO"

  OPTIND=1
  while getopts Ffbcr opts; do
    case "${opts}" in
      F)
        force="YES"
        ;;
      f)
        only_fetch="YES"
        ;;
      b)
        only_build="YES"
        ;;
      c)
        nonstop="YES"
        ;;
      r)
        resume="YES"
        ;;
    esac
  done
  shift $(( ${OPTIND} - 1 ))

  for pkg in "${@}"; do
    tmp_pkg=($( split_pkg_ver ${pkg} ))
    count="$(  grep '[/]*'${tmp_pkg[0]}'$' ${PKGLIST} | wc -l )"
    if [ ${count} -ne 1 -a "X${nonstop}" != "XYES" ]; then
      return # what return value?
    else
      continue
    fi

    pkg="$( grep '[/]*'${tmp_pkg[0]}'$' ${PKGLIST} )"
    if [ -n "${tmp_pkg[1]}" ]; then
      pkg="${ASPKG_DIR}/${pkg}/aspkg-${tmp_pkg[1]}"
    else
      pkg="${ASPKG_DIR}/${pkg}/aspkg"
    fi

    if [ ! -e "${pkg}" -a "X${nonstop}" != "XYES" ]; then
      return # what return value?
    else
      continue
    fi

    echo "${pkg}" # test prototyping

  done
}

case ${1} in
  install|in)
    shift
    do_install "$@"
    ;;
  update|up)
    shift
    do_update
    ;;
  remove|rm)
    shift
    do_remove "$@"
    ;;
  *) echo "usage: ${0}";;
esac
# vim: ft=sh:ts=4:sw=2:sts=2:syn=sh:et
